version: '3'

silent: true

tasks:

  clean:
    desc: Clean artifacts
    cmds:
      - cmd: rm -rf .docusaurus
      - cmd: rm -rf build

  start:
    desc: Start server locally
    cmds:
      - task: clean
      - cmd: npm run start

  build:
    desc: Build documentation
    cmds:
      - task: clean
      - cmd: npm run build

  preview:
    desc: Preview documentation
    cmds:
      - task: clean
      - cmd: npm run build
      - cmd: npm run serve
